# QUESTIONS
mind_question = Answer.create(question: "MIND: This aspect shows how you interact with your surroundings:", option1: "I prefer solitary activities and get exhausted by social interaction. I tend to be quite sensitive to external stimulation (e.g. sound, sight or smell) in general.", option2: "I prefer group activities and get energized by social interaction. I tend to be more enthusiastic and easily excited.")
energy_question = Answer.create(question: "ENERGY: This determines how you see the world and process information:", option1: "I am highly practical, pragmatic and down-to-earth. I tend to have strong habits and focus on what is happening or has already happened.", option2: "I am very imaginative, open-minded and curious. I prefer novelty over stability and focus on hidden meanings and future possibilities.")
nature_question = Answer.create(question: "NATURE: This determines how you make decisions and cope with emotions:", option1: "I focus on objectivity and rationality, prioritizing logic over emotions. I tend to hide my feelings and see efficiency as more important than cooperation.", option2: "I am sensitive and emotionally expressive. I am empathic, not very competitive, and tend to focus on social harmony and cooperation.")
tactics_question = Answer.create(question: "TACTICS: This reflects your approach to work, planning and decision-making:", option1: "I am decisive, thorough and highly organized. I value clarity, predictability and closure, preferring structure and planning to spontaneity.", option2: "I am very good at improvising and spotting opportunities. I tend to be flexible, relaxed, and nonconforming.  I prefer keeping my options open.")

# PERSONALITIES
intj = Personality.create(name: "INTJ", description: "INTJs have original minds and great drive for implementing their ideas and achieving their goals. They quickly see patterns in external events and develop long-range explanatory perspectives. When committed, INTJs organize a job and carry it through. Skeptical and independent, INTJs have high standards of competence and performance - for themselves and others.", nickname: "Mastermind", brief: "Imaginitive and strategic thinkers, with a plan for everything.")
intp = Personality.create(name: "INTP", description: "INTPs seek to develop logical explanations for everything that interests them. Theoretical and abstract, they're interested more in ideas than in social interaction. They are quiet, contained, flexible, and adaptable. INTPs have an unusual ability to focus in depth to solve problems in their area of interest. They are skeptical, sometimes critical, and always analytical.", nickname: "Logician", brief: "Innovative inventors with an unquenchable thirst for knowledge.")
entj = Personality.create(name: "ENTJ", description: "ENTJs are frank, decisive, and assume leadership readily. They quickly see illogical and inefficient procedures and policies and develop and implement comprehensive systems to solve organizational problems. They enjoy long-term planning and goal setting. ENTJs are usually well informed, well read, and enjoy expanding their knowledge and passing it on to others. They can be forceful in presenting their ideas.", nickname: "Commander", brief: "Bold, imaginitive and strong-willed leaders, always finding a way - or making one.")
entp = Personality.create(name: "ENTP", description: "ENTPs are quick, ingenious, stimulating, alert, and outspoken. They are resourceful in solving new and challenging problems. They are adept at generating conceptual possibilities and then analyzing them strategically. ENTPs are good at reading other people. They are bored by routine, will seldom do the same thing the same way, and are apt to turn to one new interest after another.", nickname: "Debater", brief: "Smart and curious thinkers who cannot resist an intellectual challenge.")
infj = Personality.create(name: "INFJ", description: "INFJs seek meaning and connection in ideas, relationships, and material possessions. They want to understand what motivates people and are insightful about others. They are conscientious and committed to their firm values. INFJs develop a clear vision about how best to serve the common good. They are organized and decisive in implementing their vision.", nickname: "Advocate", brief: "Quiet and mystical, yet very inspiring and tireless leaders.")
infp = Personality.create(name: "INFP", description: "INFPs are idealistic, loyal to their values and to people who are important to them. They want an external life that is congruent with their values. They are curious, quick to see possibilities and can be catalysts for implementing ideas. They seek to understand people and to help them fulfill their potential. INFPs are adaptable, flexible, and accepting unless a value is threatened.", nickname: "Mediator", brief: "Poetic, kind and altruistic people, always eager to help a good cause.")
enfj = Personality.create(name: "ENFJ", description: "ENFJs are warm, empathetic, responsive, and responsible. They are highly attuned to the emotions, needs, and motivations of others. They find potential in everyone and want to help others fulfill their potential. ENFJs may act as catalysts for individual and group growth. They are loyal and responsive to praise and criticism. ENFJs are sociable, facilitate others in a group, and provide inspiring leadership.", nickname: "Protagonist", brief: "Charismatic and inspiring leaders, able to mesmerize their listeners.")
enfp = Personality.create(name: "ENFP", description: "ENFPs are warmly enthusiastic and imaginative. They see life as full of possibilities. They make connections between events and information very quickly, and confidently proceed based on the patterns they see. ENFPs want a lot of affirmation from others, and readily give appreciation and support. They are spontaneous and flexible and often rely on their ability to improvise and their verbal fluency.", nickname: "Campaigner", brief: "Enthusiastic, creative and sociable free spirits, who can always find a reason to smile.")
istj = Personality.create(name: "ISTJ", description: "ISTJs are quiet, serious, and earn success by thoroughness and dependability. They are practical, matter-of-fact, realistic, and responsible. They decide logically what should be done and work toward it steadily, regardless of distractions. ISTJs take pleasure in making everything orderly and organized - their work, their home, their life. They value traditions and loyalty.", nickname: "Logistician", brief: "Practical and fact-minded individuals, whose reliability cannot be doubted.")
isfj = Personality.create(name: "ISFJ", description: "ISFJs are quiet, friendly, responsible, and conscientious. They are committed and steady in meeting their obligations. ISFJs are thorough, painstaking, and accurate. They are loyal, considerate, and notice and remember specifics about people who are important to them. They are concerned with how others feel. They strive to create an orderly and harmonious environment at work and at home.", nickname: "Defender", brief: "Very dedicated and warm protectors, always ready to defend their loved ones.")
estj = Personality.create(name: "ESTJ", description: "ESTJs are practical, realistic, matter-of-fact. They are decisive and quickly move to implement decisions. ESTJs organize projects and people to get things done and focus on getting results in the most efficient way possible. They take care of routine details and have a clear set of logical standards, systematically follow them and want others to also. They can be forceful in implementing their plans.", nickname: "Executive", brief: "Excellent administrators, unsurpassed at managing things - or people.")
esfj = Personality.create(name: "ESFJ", description: "ESFJs are warmhearted, conscientious, and cooperative. They want harmony in their environment and work with determination to establish it. They like to work with others to complete tasks accurately and on time. They are loyal and follow through even in small matters. ESFJs notice what others need in their day-by-day lives and try to provide it. They want to be appreciated for who they are and for what they contribute.", nickname: "Consul", brief: "Extraordinarily caring, social and popular people, always eager to help.")
istp = Personality.create(name: "ISTP", description: "ISTPs are tolerant and flexible, and act as quiet observers until a problem appears, then act quickly to find workable solutions. They analyze what makes things work and readily get through large amounts of data to isolate the core of practical problems. They are interested in cause and effect, organizing facts using logical principles, and value efficiency.", nickname: "Virtuoso", brief: "Bold and practical experimenters, masters of all kinds of tools.")
isfp = Personality.create(name: "ISFP", description: "ISFPs are quiet, friendly, sensitive, and kind. They enjoy the present moment. They like to have their own space and to work within their own time frame. They are loyal and committed to their values and to people who are important to them. ISFPs dislike disagreements and conflicts and do not force their opinions or values on others.", nickname: "Adventurer", brief: "Flexible and charming artists, always ready to explore and experience something new.")
estp = Personality.create(name: "ESTP", description: "ESTPs are flexible and tolerant, and take a pragmatic approach focused on immediate results. Theories and conceptual explanations bore them - they want to act energetically to solve the problem. They focus on the here-and-now, are spontaneous, and enjoy each moment that they can be active with others. They enjoy material comforts and style. ESTPs learn best through doing.", nickname: "Entrepreneur", brief: "Smart, energetic and very perceptive people, who truly enjoy living on the edge.")
esfp = Personality.create(name: "ESFP", description: "ESFPs are outgoing, friendly, and accepting. They are exuberant lovers of life, people, and material comforts. They enjoy working with others to make things happen. ESFPs bring common sense and a realistic approach to their work, and make work fun. They are flexible and spontaneous and adapt readily to new people and environments. ESFPs learn best by trying a new skill with other people.", nickname: "Entertainer", brief: "Spontaneous, energetic and enthusiastic people - life is never boring around them.")

# USERS
# christina = User.create(username: "christina_mcm", name: "Christina McMahon", bio: "I'm a student at Flatiron School.", personality_id: nil)
# sean = User.create(username: "sean_stamm", name: "Sean Stamm", bio: "I'm a software engineer at Teleion.", personality_id: nil)

# FRIENDS

puts "done"